CREATE TABLE IF NOT EXIST persons (
 id BIGINIT AUTO_INCREMENT PRIMARY KEY,
 rut VARCHAR(20) NOT NULL UNIQUE,
 nombre VARCHAR(100) NOT NULL,
 apellido VARCHAR(100) NOT NULL,
 fecha_nacimiento DATE NOT NULL,
 calle VARCHAR (200),
 comuna VARCHAR(100),
 region VARCHAR(100),
);