spring:
  datasource:
    url: jdbc:h2:mem:persondb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update   # Crea o actualiza tablas si no existen
    show-sql: true
    properties:
      hibernate.format_sql: true
  sql:
    init:
      mode: always       # Ejecuta schema.sql y data.sql en cada arranque